version: "3"

services:
  quoted-api:
    build: .
    depends_on:
      - quoted-db
    ports:
      - 5000:5000
    environment:
      - MONGODB_HOST=mongodb://quoted-db/quoted

  quoted-db:
    image: mongo:4.2.0
